version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    container_name: testimonials-app
    depends_on:
      - database
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - mynetwork
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:

networks:
  mynetwork:
